### ISSUE TITLE
await profile.get_clan() issue (what is this?)

### ISSUE THREAD

**Issue by SharpBit** [grokkers/cr-async#8]
```
2017-10-29T19:40:45.894855+00:00 app[worker.1]: Ignoring exception in command profile:
2017-10-29T19:40:45.895155+00:00 app[worker.1]: Traceback (most recent call last):
2017-10-29T19:40:45.895219+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
2017-10-29T19:40:45.895221+00:00 app[worker.1]:     ret = yield from coro(*args, **kwargs)
2017-10-29T19:40:45.895240+00:00 app[worker.1]:   File "/app/cogs/profile.py", line 38, in profile
2017-10-29T19:40:45.895241+00:00 app[worker.1]:     clan = await profile.get_clan()
2017-10-29T19:40:45.895267+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/crasync/core.py", line 92, in get_clan
2017-10-29T19:40:45.895269+00:00 app[worker.1]:     data = await self.request(url)
2017-10-29T19:40:45.895286+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/crasync/core.py", line 56, in request
2017-10-29T19:40:45.895287+00:00 app[worker.1]:     data = await resp.json()
2017-10-29T19:40:45.895307+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 730, in json
2017-10-29T19:40:45.895308+00:00 app[worker.1]:     headers=self.headers)
2017-10-29T19:40:45.895352+00:00 app[worker.1]: aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; 
```

**Comment by fourjr** [comment]
most likely a temp api down issue, @verixx please look into this

**Comment by fourjr** [comment]
That's a connection issue to the API.
